Selenium 4 changes
browserstack/java-selenium-browserstack pull request #2
Opened 2022-04-08 04:33 UTC by RutvikChandla

2022-04-08 08:32 UTC, karanshah-browserstack requested changes

2022-04-08 08:32 UTC, karanshah-browserstack commented on pom.xml
> +  <url>http://www.example.com</url>
browserstack.com instead of example.com

2022-04-08 08:32 UTC, karanshah-browserstack commented on src/test/java/com/browserstack/app/JavaLocalSample.java
> +  public static final String AUTOMATE_ACCESS_KEY = "AXHzyg34Qr81Nep231pu";
Remove username and accesskey

2022-04-08 08:32 UTC, karanshah-browserstack commented on src/test/java/com/browserstack/app/JavaLocalSample.java
> +}
EOL

2022-04-08 08:32 UTC, karanshah-browserstack commented on src/test/java/com/browserstack/app/JavaParallelSample.java
> +class DeviceThree implements Runnable {
Can we create this dynamically? This looks very odd and repeated code.

2022-04-08 08:32 UTC, karanshah-browserstack commented on src/test/java/com/browserstack/app/JavaSample.java
> +  public static final String AUTOMATE_USERNAME = "rutvikchandla_2MEern";
Remove username and accesskey

2022-04-08 08:32 UTC, karanshah-browserstack commented on src/test/java/com/browserstack/app/JavaSample.java
> +}
EOL

2022-04-08 08:32 UTC, karanshah-browserstack requested changes

2022-04-08 08:32 UTC, karanshah-browserstack commented on README copy.md
> +---
Rename file to README.md

2022-04-17 14:05 UTC, RutvikChandla commented
@karanshah-browserstack have done the changes please review.

2022-04-18 06:24 UTC, karanshah-browserstack requested changes

2022-04-18 06:24 UTC, karanshah-browserstack commented on src/test/java/com/browserstack/app/JavaLocalSample.java
> +bsLocalArgs.put("key", "AXHzyg34Qr81Nep231pu");
Remove this

2022-04-18 06:34 UTC, RutvikChandla commented on src/test/java/com/browserstack/app/JavaLocalSample.java
> +bsLocalArgs.put("key", "AXHzyg34Qr81Nep231pu");
Resolved

2022-04-18 06:36 UTC, karanshah-browserstack approved these changes

2022-04-18 12:48 UTC, merged